spaces=' '*25
print('%s 12 Butts Wynd' %spaces)
print('%s Twinklebottom Health'%spaces)
print('%s West Snoring' %spaces)
print()
print()
print('Dear Sir')
print()
print('I wish to report that tiles are missing from the')
print('outside the toilet roof.')
print('I think it was the bad wind the other night that blew them away.')
print()
print('Regards')
print('Sheldon cooper')

